package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/nemesisesq/vaux_server/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (MessageSound)
// DB Table: Plural (message_sounds)
// Resource: Plural (MessageSounds)
// Path: Plural (/message_sounds)
// View Template Folder: Plural (/templates/message_sounds/)

// MessageSoundsResource is the resource for the MessageSound model
type MessageSoundsResource struct {
	buffalo.Resource
}

// List gets all MessageSounds. This function is mapped to the path
// GET /message_sounds
func (v MessageSoundsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	messageSounds := &models.MessageSounds{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all MessageSounds from the DB
	if err := q.All(messageSounds); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, messageSounds))
}

// Show gets the data for one MessageSound. This function is mapped to
// the path GET /message_sounds/{message_sound_id}
func (v MessageSoundsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty MessageSound
	messageSound := &models.MessageSound{}

	// To find the MessageSound the parameter message_sound_id is used.
	if err := tx.Find(messageSound, c.Param("message_sound_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, messageSound))
}

// New renders the form for creating a new MessageSound.
// This function is mapped to the path GET /message_sounds/new
func (v MessageSoundsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.MessageSound{}))
}

// Create adds a MessageSound to the DB. This function is mapped to the
// path POST /message_sounds
func (v MessageSoundsResource) Create(c buffalo.Context) error {
	// Allocate an empty MessageSound
	messageSound := &models.MessageSound{}

	// Bind messageSound to the html form elements
	if err := c.Bind(messageSound); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(messageSound)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, messageSound))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "MessageSound was created successfully")

	// and redirect to the message_sounds index page
	return c.Render(201, r.Auto(c, messageSound))
}

// Edit renders a edit form for a MessageSound. This function is
// mapped to the path GET /message_sounds/{message_sound_id}/edit
func (v MessageSoundsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty MessageSound
	messageSound := &models.MessageSound{}

	if err := tx.Find(messageSound, c.Param("message_sound_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, messageSound))
}

// Update changes a MessageSound in the DB. This function is mapped to
// the path PUT /message_sounds/{message_sound_id}
func (v MessageSoundsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty MessageSound
	messageSound := &models.MessageSound{}

	if err := tx.Find(messageSound, c.Param("message_sound_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind MessageSound to the html form elements
	if err := c.Bind(messageSound); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(messageSound)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, messageSound))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "MessageSound was updated successfully")

	// and redirect to the message_sounds index page
	return c.Render(200, r.Auto(c, messageSound))
}

// Destroy deletes a MessageSound from the DB. This function is mapped
// to the path DELETE /message_sounds/{message_sound_id}
func (v MessageSoundsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty MessageSound
	messageSound := &models.MessageSound{}

	// To find the MessageSound the parameter message_sound_id is used.
	if err := tx.Find(messageSound, c.Param("message_sound_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(messageSound); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "MessageSound was destroyed successfully")

	// Redirect to the message_sounds index page
	return c.Render(200, r.Auto(c, messageSound))
}
